# Funkcije filtriranja

In [6]:
import numpy as np
niz=np.linspace(-4,4,9)
niz

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [7]:
np.where(niz<0, niz**2, niz**3)        # na mjestu gdje je ispunjen uvjet <0 napravi kvadrat, ako nije ispunjen kubiraj

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

## Zadatak
- manji od -1, kvadrat
- manji od 2, na treću potenciju
- veći/jednaki 2: na 4 potenciju

In [9]:
np.select([],[])  #prva lista uvjeti, druga lista:radnje koje odgovaraju uvjetima


ValueError: select with an empty condition list is not possible

In [11]:
x=np.linspace(-4,4,9)
np.select([x<-1, x<2,x>=2],[x**2,x**3,x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [14]:
brojevi=np.random.randint(6, size=20)
brojevi


array([1, 3, 5, 3, 1, 5, 2, 2, 3, 1, 2, 1, 2, 4, 2, 3, 1, 4, 4, 4])

In [16]:
np.unique(brojevi)

array([1, 2, 3, 4, 5])

In [18]:
niz_64 = np.arange(1,65).reshape(8,8)
niz_64


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [31]:
np.flip(niz_64)

array([[64, 63, 62, 61, 60, 59, 58, 57],
       [56, 55, 54, 53, 52, 51, 50, 49],
       [48, 47, 46, 45, 44, 43, 42, 41],
       [40, 39, 38, 37, 36, 35, 34, 33],
       [32, 31, 30, 29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12, 11, 10,  9],
       [ 8,  7,  6,  5,  4,  3,  2,  1]])

In [37]:
np.flipud(niz_64)

array([[57, 58, 59, 60, 61, 62, 63, 64],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

In [35]:
np.fliplr(niz_64)

array([[ 8,  7,  6,  5,  4,  3,  2,  1],
       [16, 15, 14, 13, 12, 11, 10,  9],
       [24, 23, 22, 21, 20, 19, 18, 17],
       [32, 31, 30, 29, 28, 27, 26, 25],
       [40, 39, 38, 37, 36, 35, 34, 33],
       [48, 47, 46, 45, 44, 43, 42, 41],
       [56, 55, 54, 53, 52, 51, 50, 49],
       [64, 63, 62, 61, 60, 59, 58, 57]])

In [26]:
niz_a=np.random.rand(4,6)
niz_a=np.round(niz_a,2)
niz_a


array([[0.93, 0.75, 0.19, 0.99, 0.49, 0.4 ],
       [0.98, 0.92, 0.95, 0.94, 0.73, 0.33],
       [0.5 , 0.36, 0.67, 0.78, 0.43, 0.99],
       [0.51, 0.94, 0.43, 0.  , 0.71, 0.61]])

In [27]:
np.sort(niz_a, axis=0)

array([[0.5 , 0.36, 0.19, 0.  , 0.43, 0.33],
       [0.51, 0.75, 0.43, 0.78, 0.49, 0.4 ],
       [0.93, 0.92, 0.67, 0.94, 0.71, 0.61],
       [0.98, 0.94, 0.95, 0.99, 0.73, 0.99]])

In [28]:
np.sort(niz_a, axis=1)

array([[0.19, 0.4 , 0.49, 0.75, 0.93, 0.99],
       [0.33, 0.73, 0.92, 0.94, 0.95, 0.98],
       [0.36, 0.43, 0.5 , 0.67, 0.78, 0.99],
       [0.  , 0.43, 0.51, 0.61, 0.71, 0.94]])

In [29]:
niz_64


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

# Spremanje u txt datoteku

In [44]:
np.savetxt('niz_64.txt', niz_64, '%4.0f', header='', footer='')   
# '%4.0f' format zapisa jer po default daje znanstveni zapis E00

In [42]:
mnozenje = lambda x,y:x*y
tablica_mnozenja=np.fromfunction(mnozenje, (11,11), dtype=np.int32)
tablica=tablica_mnozenja[1:11, 1:11]         
tablica

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [54]:
import datetime as dt
np.savetxt('tablica_množenja.txt', tablica, '%4.0f', header='''Naziv datoteke: "tablica_množenja.txt"\n
Autor: Sandra\n
----------------------------------------------------''', footer='''--------------------------------------\n''' +str(dt.datetime.now())
)
